name: Horilla Vainilla CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: horilla_test
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: horilla_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r horilla_data/requirements.txt
    
    - name: Run migrations
      env:
        DATABASE_URL: postgresql://horilla_test:test_password@localhost:5432/horilla_test
      run: |
        cd horilla_data
        python manage.py migrate

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Build Docker image
      run: |
        docker-compose build
    
    - name: Test Docker build
      run: |
        docker-compose up -d
        sleep 30
        docker-compose ps
        docker-compose down
